module.exports = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  CREATE_GROUP: 'CREATE_GROUP',
  ADDUSER_GROUP: 'ADDUSER_GROUP',
  ADD_MESSAGE: 'ADD_MESSAGE',
  SIGNOUT_USER: 'SIGNOUT_USER',
  RECEIVE_USER_RESULTS: 'RECEIVE_USER_RESULTS',
  RECEIVE_MESSAGE_RESULTS: 'RECEIVE_MESSAGE_RESULTS',
  RECEIVE_GROUP_RESULTS: 'RECEIVE_GROUP_RESULTS',
  RECEIVE_ERRORS: 'RECEIVE_ERRORS',
  RECEIVE_SUCCESS: 'RECEIVE_SUCCESS',
  RECEIVE_LOGIN_ERRORS: 'RECEIVE_LOGIN_ERRORS'

};
